### ISSUE TITLE
Is UDM Basic affected?

### ISSUE THREAD

**Issue by OpenSourceGhost** [fire1ce/UDM-Persistent-SSH-Keys#3]
I ask because UDM Basic doesn't seem to discard SSH keys after reboot. I create my own public key for "\root\.ssh\authorized_keys" file and use same one for "\mnt\data\ssh\id_rsa.pub" . Private key is placed in "\mnt\data\ssh\id_rsa".

**Comment by fire1ce** [comment]
UDM Basic might not be affected. if the keys persistent after reboot, you don't need this workaround. 
If you have no issues, close this one. 
Have a great day!

**Comment by fire1ce** [comment]
You should not mess with id_rsa* files at UDM They are used to ssh to Access points. 
The only file you should mass with is the `authorized_keys` used by the ssh service. That should include your public key. 
Read the code of the scrip to understand the logic.

**Comment by 7ArxS2PrqAUF9Gom** [comment]
Just FYI, after factory reset, UDM basic generates "\mnt\data\ssh\id_rsa", "\mnt\data\ssh\id_rsa.pub" and makes it "id_rsa" identical to "\root\.ssh\authorized_keys". They are simply copies of each other. To generate new "id_rsa" and "id_rsa.pub" and "authorized_keys" files, one needs to delete them and reboot, but it is quite disturbing to allow both public and private keys to exist on server. It is also disturbing to make AP "id_rsa.pub" to be identical to "\root\.ssh\authorized_keys" . That means remote WAN access over SSH uses the same private key as local root SSH access...

This script is so great! Upon reboot, it adds user-generated "authorized_keys" from "onboot.d" directory into UDM's "/root/.ssh/authorized_keys" file. The result is having 2 (self-generated and UDM-generated) keys in "/root/.ssh/authorized_keys" after reboot.

What would be great is either having another script or create a different version that deletes UDM-generated "id_rsa" and "id_rsa.pub" and makes sure "id_rsa" does not exist in "\root\.ssh\authorized_keys". Doing so prevents AP SSH access from WAN, but makes it secure for local SSH access because it assures that only client/user has the private key and UDM has only the public key. I wish

**Comment by fire1ce** [comment]
FYI, you have basic miss understanding how ssh keys keys works. You have some homework do to before you write stuff like u did
